#!/usr/bin/env python3
"""Generates src/config/config_tables.inc from minio-config.json, MinIO's
config registry as zz_buckets_config_dump_test.go prints it.

  python3 tools/configgen/gen.py > src/config/config_tables.inc
"""
import json, os, sys

here = os.path.dirname(os.path.abspath(__file__))
subs = json.load(open(os.path.join(here, 'minio-config.json')))

def c(s):
    return json.dumps(s, ensure_ascii=False)  # a valid C string literal for these inputs

def b(v):
    return 'true' if v else 'false'

out = ['/* Generated by tools/configgen/gen.py from MinIO RELEASE.2025-10-15T17-29-55Z. DO NOT EDIT. */']
for s in subs:
    out.append('static const cfg_key_def k_keys_%s[] = {' % s['Name'])
    for k in s['Keys']:
        out.append('    {%s, %s, %s, %s, %s, %s, %s, %s},' % (c(k['Key']), c(k['Default']), c(k['Type']),
                   c(k['Description']), b(k['HiddenIfEmpty']), b(k['Optional']), b(k['Sensitive']), b(k['Secret'])))
    out.append('};')
out.append('static const cfg_subsys_def k_subsystems[] = {')
for s in subs:
    out.append('    {%s, %s, %s, %s, %s, %s, k_keys_%s, %d},' % (c(s['Name']), c(s['Description']),
               b(s['MultipleTargets']), b(s['Dynamic']), b(s['SingleTarget']), b(bool(s['Description'])),
               s['Name'], len(s['Keys'])))
out.append('};')
out.append('#define K_SUBSYSTEMS_N %d' % len(subs))
sys.stdout.write('\n'.join(out) + '\n')
