// Command policygen emits C tables and golden vectors for Buckets' IAM
// policy engine from MinIO's own github.com/minio/pkg/v3/policy (v3.1.3,
// the version MinIO RELEASE.2025-10-15 links):
//
//	cd tools/policygen && go run . tables  > ../../src/iam/policy_tables.inc
//	cd tools/policygen && go run . vectors > ../../tests/unit/policy_vectors.inc
//
// Tables are derived from the package's behaviour, not transcribed: every
// string constant in its sources is classified with the package's own
// predicates, and per-action condition keys are probed through Validate.
// Vectors are random policies and requests evaluated by the real library.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"math/rand"
	"os"
	"path/filepath"
	"runtime/debug"
	"sort"
	"strconv"
	"strings"

	"github.com/minio/pkg/v3/policy"
	"github.com/minio/pkg/v3/policy/condition"
	"github.com/minio/pkg/v3/wildcard"
)

func pkgDir() string {
	info, _ := debug.ReadBuildInfo()
	for _, d := range info.Deps {
		if d.Path == "github.com/minio/pkg/v3" {
			return filepath.Join(os.Getenv("GOMODCACHE"), "github.com/minio/pkg/v3@"+d.Version)
		}
	}
	panic("minio/pkg not found")
}

// Every string constant in the policy package (and its condition package).
func stringConstants(dir string) []string {
	fset := token.NewFileSet()
	seen := map[string]bool{}
	for _, sub := range []string{"policy", "policy/condition"} {
		pkgs, err := parser.ParseDir(fset, filepath.Join(dir, sub), func(fi os.FileInfo) bool {
			return !strings.HasSuffix(fi.Name(), "_test.go")
		}, 0)
		if err != nil {
			panic(err)
		}
		for _, p := range pkgs {
			ast.Inspect(p, func(n ast.Node) bool {
				if bl, ok := n.(*ast.BasicLit); ok && bl.Kind == token.STRING {
					if s, err := strconv.Unquote(bl.Value); err == nil {
						seen[s] = true
					}
				}
				return true
			})
		}
	}
	out := []string{}
	for s := range seen {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

func cstr(s string) string { return strconv.Quote(s) }

func validates(stmt map[string]any) bool {
	doc, _ := json.Marshal(map[string]any{"Version": "2012-10-17", "Statement": []any{stmt}})
	_, err := policy.ParseConfig(bytes.NewReader(doc))
	return err == nil
}

func tables() {
	consts := stringConstants(pkgDir())
	var s3, obj, admin, sts, kms []string
	for _, c := range consts {
		if strings.ContainsAny(c, "*?") && c != "s3:*" && c != "admin:*" && c != "sts:*" && c != "kms:*" {
			continue
		}
		a := policy.Action(c)
		switch {
		case strings.HasPrefix(c, "s3:") && a.IsValid() && !strings.ContainsAny(c[3:], "*?") || c == "s3:*":
			s3 = append(s3, c)
			if a.IsObjectAction() {
				obj = append(obj, c)
			}
		case strings.HasPrefix(c, "admin:") && policy.AdminAction(c).IsValid():
			admin = append(admin, c)
		case strings.HasPrefix(c, "sts:") && policy.STSAction(c).IsValid():
			sts = append(sts, c)
		case strings.HasPrefix(c, "kms:") && policy.KMSAction(c).IsValid():
			kms = append(kms, c)
		}
	}
	keys := []string{}
	for _, k := range condition.AllSupportedKeys {
		keys = append(keys, string(k))
	}
	common := map[string]bool{}
	for _, k := range condition.CommonKeys {
		common[string(k)] = true
	}
	keyIndex := map[string]int{}
	for i, k := range keys {
		keyIndex[k] = i
	}

	w := os.Stdout
	fmt.Fprintln(w, "/* Generated by tools/policygen from github.com/minio/pkg/v3 v3.1.3 policy. DO NOT EDIT. */")
	emit := func(name string, list []string) {
		fmt.Fprintf(w, "static const char *const %s[] = {\n", name)
		for _, s := range list {
			fmt.Fprintf(w, "    %s,\n", cstr(s))
		}
		fmt.Fprintf(w, "};\n#define %s_N %d\n", strings.ToUpper(name), len(list))
	}
	emit("k_s3_actions", s3)
	emit("k_object_actions", obj)
	emit("k_admin_actions", admin)
	emit("k_sts_actions", sts)
	emit("k_kms_actions", kms)
	emit("k_cond_keys", keys)
	fmt.Fprintf(w, "/* Bit i: k_cond_keys[i] is a common key (usable with any action, substituted in resources). */\n")
	fmt.Fprintf(w, "static const bool k_cond_common[] = {")
	for _, k := range keys {
		fmt.Fprintf(w, "%v,", common[k])
	}
	fmt.Fprintln(w, "};")

	// Condition keys each action accepts, probed through Validate.
	probe := func(action string, resource bool) []bool {
		allowed := make([]bool, len(keys))
		for i, k := range keys {
			st := map[string]any{"Effect": "Allow", "Action": action,
				"Condition": map[string]any{"Null": map[string]any{k: "true"}}}
			if resource {
				st["Resource"] = "arn:aws:s3:::*"
			}
			allowed[i] = validates(st)
		}
		return allowed
	}
	emitKeys := func(name string, actions []string, resource bool) {
		fmt.Fprintf(w, "static const bool %s[][%d] = {\n", name, len(keys))
		for _, a := range actions {
			fmt.Fprintf(w, "    {")
			for _, b := range probe(a, resource) {
				if b {
					fmt.Fprint(w, "1,")
				} else {
					fmt.Fprint(w, "0,")
				}
			}
			fmt.Fprintf(w, "}, /* %s */\n", a)
		}
		fmt.Fprintln(w, "};")
	}
	emitKeys("k_s3_action_keys", s3, true)
	emitKeys("k_admin_action_keys", admin, false)
	emitKeys("k_sts_action_keys", sts, false)
	_ = keyIndex
}

// ---- vectors ----

var rng = rand.New(rand.NewSource(20260928))

func pick[T any](xs []T) T { return xs[rng.Intn(len(xs))] }

var actionPool = []string{"s3:*", "s3:GetObject", "s3:PutObject", "s3:ListBucket", "s3:Get*", "s3:*Object",
	"s3:DeleteObject", "s3:GetObjectVersion", "s3:ListAllMyBuckets", "s3:GetBucketLocation", "s3:List*",
	"s3:CreateBucket", "s3:PutObjectTagging", "s3:?etObject"}
var resourcePool = []string{"arn:aws:s3:::*", "arn:aws:s3:::photos", "arn:aws:s3:::photos/*", "arn:aws:s3:::photos/2024/*",
	"arn:aws:s3:::pho*", "arn:aws:s3:::*/public/*", "arn:aws:s3:::home/${aws:username}/*", "arn:aws:s3:::home/${aws:username}",
	"arn:aws:s3:::docs/?.txt", "arn:aws:s3:::docs", "arn:aws:s3:::${aws:username}", "arn:aws:s3:::*/*", "*"}

func randCondition() map[string]any {
	switch rng.Intn(9) {
	case 0:
		return map[string]any{"StringEquals": map[string]any{"s3:prefix": pick([]any{"", "2024/", []string{"a/", "b/"}})}}
	case 1:
		return map[string]any{"StringLike": map[string]any{"s3:prefix": pick([]any{"2024/*", "*", []string{"a*", "b?"}})}}
	case 2:
		return map[string]any{"IpAddress": map[string]any{"aws:SourceIp": pick([]any{"10.0.0.0/8", "192.168.1.5", []string{"10.1.0.0/16", "172.16.0.0/12"}})}}
	case 3:
		return map[string]any{"NotIpAddress": map[string]any{"aws:SourceIp": "10.0.0.0/8"}}
	case 4:
		return map[string]any{"Bool": map[string]any{"aws:SecureTransport": pick([]any{"true", "false", true})}}
	case 5:
		return map[string]any{"Null": map[string]any{"s3:prefix": pick([]any{"true", "false"})}}
	case 6:
		return map[string]any{"StringNotEquals": map[string]any{"aws:username": pick([]any{"alice", []string{"bob", "carol"}})}}
	case 7:
		return map[string]any{"NumericLessThanEquals": map[string]any{"s3:max-keys": pick([]any{"10", 100})}}
	default:
		return map[string]any{pick([]string{"ForAnyValue:StringEquals", "ForAllValues:StringEquals", "StringEqualsIgnoreCase"}):
			map[string]any{"aws:username": pick([]any{"Alice", []string{"alice", "bob"}})}}
	}
}

func randStatement() map[string]any {
	st := map[string]any{"Effect": pick([]string{"Allow", "Allow", "Deny"})}
	acts := []string{}
	for n := 1 + rng.Intn(3); len(acts) < n; {
		a := pick(actionPool)
		if !contains(acts, a) {
			acts = append(acts, a)
		}
	}
	if rng.Intn(8) == 0 {
		st["NotAction"] = acts
	} else if len(acts) == 1 && rng.Intn(2) == 0 {
		st["Action"] = acts[0]
	} else {
		st["Action"] = acts
	}
	res := []string{}
	for n := 1 + rng.Intn(2); len(res) < n; {
		r := pick(resourcePool)
		if !contains(res, r) {
			res = append(res, r)
		}
	}
	if rng.Intn(8) == 0 {
		st["NotResource"] = res
	} else {
		st["Resource"] = res
	}
	if rng.Intn(3) == 0 {
		st["Condition"] = randCondition()
	}
	return st
}

func contains(xs []string, x string) bool {
	for _, y := range xs {
		if x == y {
			return true
		}
	}
	return false
}

type args struct {
	Action, Bucket, Object string
	Owner                  bool
	Cond                   map[string][]string
}

func randArgs() args {
	a := args{Action: pick([]string{"s3:GetObject", "s3:PutObject", "s3:ListBucket", "s3:DeleteObject",
		"s3:GetObjectVersion", "s3:ListAllMyBuckets", "s3:GetBucketLocation", "s3:CreateBucket", "s3:PutObjectTagging"}),
		Bucket: pick([]string{"photos", "docs", "home", "alice", "other", ""}),
		Object: pick([]string{"", "", "2024/a.jpg", "public/x", "alice/notes", "a.txt", "ab.txt", "bob/x", "2024/", "/lead", "x/../y"}),
		Owner:  rng.Intn(10) == 0, Cond: map[string][]string{}}
	if rng.Intn(2) == 0 {
		a.Cond["prefix"] = []string{pick([]string{"", "2024/", "a/", "bb", "2024/x"})}
	}
	if rng.Intn(2) == 0 {
		a.Cond["SourceIp"] = []string{pick([]string{"10.1.2.3", "192.168.1.5", "172.20.0.1", "8.8.8.8", "::1", "junk"})}
	}
	if rng.Intn(2) == 0 {
		a.Cond["SecureTransport"] = []string{pick([]string{"true", "false"})}
	}
	if rng.Intn(2) == 0 {
		a.Cond["username"] = []string{pick([]string{"alice", "bob", "Alice", ""})}
	}
	if rng.Intn(3) == 0 {
		a.Cond["max-keys"] = []string{pick([]string{"5", "10", "1000", "x"})}
	}
	if rng.Intn(4) == 0 && len(a.Cond["username"]) > 0 {
		a.Cond["username"] = append(a.Cond["username"], "carol")
	}
	return a
}

func condC(m map[string][]string) string {
	keys := []string{}
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		b.WriteString(k)
		b.WriteString("=")
		b.WriteString(strings.Join(m[k], ","))
		b.WriteString(";")
	}
	return b.String()
}

func vectors() {
	w := os.Stdout
	fmt.Fprintln(w, "/* Generated by tools/policygen from github.com/minio/pkg/v3 v3.1.3. DO NOT EDIT. */")
	// Wildcard matching.
	fmt.Fprintln(w, "static const struct { const char *pattern, *name; bool match; } k_wildcard_vectors[] = {")
	pats := []string{"", "*", "a*", "*b", "a?c", "a*c*e", "?", "??", "*?", "a*?", "photos/*", "*.txt", "a\\*"}
	names := []string{"", "a", "ab", "abc", "abcde", "ace", "b", "photos/x", "photos", "x.txt", ".txt", "a*"}
	for _, p := range pats {
		for _, n := range names {
			fmt.Fprintf(w, "    {%s, %s, %v},\n", cstr(p), cstr(n), wildcard.Match(p, n))
		}
	}
	fmt.Fprintln(w, "};")

	// Parse validity of hand-written and random documents.
	docs := []string{
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:GetObject"],"Resource":["arn:aws:s3:::b/*"]}]}`,
		`{"version":"2012-10-17","statement":[{"effect":"Allow","action":"s3:*","resource":"arn:aws:s3:::*"}]}`,
		`{"Version":"2008-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:Nope","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::/b"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Extra":1}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}],"Bogus":true}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":[],"Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","NotAction":"s3:PutObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","NotResource":"arn:aws:s3:::c/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":["arn:aws:s3:::b/*","arn:aws:s3:::b/*"]}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListBucket","Resource":"arn:aws:s3:::b","Condition":{"StringEquals":{"s3:prefix":"x"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Condition":{"StringEquals":{"s3:prefix":"x"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListBucket","Resource":"arn:aws:s3:::b","Condition":{"StringEquals":{"s3:nokey":"x"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListBucket","Resource":"arn:aws:s3:::b","Condition":{"Nope":{"s3:prefix":"x"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListBucket","Resource":"arn:aws:s3:::b","Condition":{}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListBucket","Resource":"arn:aws:s3:::b","Condition":{"StringEquals":{"s3:prefix":5}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListBucket","Resource":"arn:aws:s3:::b","Condition":{"StringEquals":{"s3:prefix":["a","a"]}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListBucket","Resource":"arn:aws:s3:::b","Condition":{"StringEquals":{"s3:prefix":[]}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Condition":{"IpAddress":{"aws:SourceIp":"10.0.0.0/33"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Condition":{"IpAddress":{"aws:username":"10.0.0.0/8"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Condition":{"Bool":{"aws:SecureTransport":"yes"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Condition":{"ForAll:StringEquals":{"aws:username":"a"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"admin:ServerInfo"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"admin:*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"admin:Nope"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["admin:ServerInfo","s3:GetObject"],"Resource":"arn:aws:s3:::*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Sid":"good-sid_1","Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Sid":"bad sid!","Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}}`,
		`{"Version":"2012-10-17","Statement":[]}`,
		`{"Version":"2012-10-17"}`,
		`{}`,
		`[]`,
		`not json`,
		`{"Version":"2012-10-17","ID":"x","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Condition":{"StringEquals":{"s3:x-amz-server-side-encryption":"rot13"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:PutObject","Resource":"arn:aws:s3:::b/*","Condition":{"StringEquals":{"s3:x-amz-server-side-encryption":"AES256"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:PutObject","Resource":"arn:aws:s3:::b/*","Condition":{"NumericLessThan":{"s3:max-keys":"x"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListBucket","Resource":"arn:aws:s3:::b","Condition":{"NumericLessThan":{"s3:max-keys":["1","2"]}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Condition":{"DateLessThan":{"aws:CurrentTime":"2030-01-01T00:00:00Z"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*","Condition":{"DateLessThan":{"aws:CurrentTime":"2030-01-01"}}}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"},{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"kms:*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"sts:AssumeRole"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::b/${aws:username}/*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"*"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:minio:kms:::k"}]}`,
		`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::"}]}`,
	}
	for i := 0; i < 300; i++ {
		sts := []any{}
		for n := 1 + rng.Intn(3); len(sts) < n; {
			sts = append(sts, randStatement())
		}
		d, _ := json.Marshal(map[string]any{"Version": "2012-10-17", "Statement": sts})
		docs = append(docs, string(d))
	}
	fmt.Fprintln(w, "static const struct { const char *doc; bool valid; } k_parse_vectors[] = {")
	var valid []*policy.Policy
	var validDocs []string
	for _, d := range docs {
		p, err := policy.ParseConfig(strings.NewReader(d))
		fmt.Fprintf(w, "    {%s, %v},\n", cstr(d), err == nil)
		if err == nil {
			valid = append(valid, p)
			validDocs = append(validDocs, d)
		}
	}
	fmt.Fprintln(w, "};")

	// Evaluation.
	fmt.Fprintln(w, "static const struct { int doc; const char *action, *bucket, *object; bool owner; const char *cond; bool allowed; } k_eval_vectors[] = {")
	for i := 0; i < 6000; i++ {
		pi := rng.Intn(len(valid))
		a := randArgs()
		allowed := valid[pi].IsAllowed(policy.Args{Action: policy.Action(a.Action), BucketName: a.Bucket,
			ObjectName: a.Object, IsOwner: a.Owner, ConditionValues: a.Cond})
		idx := -1
		for j, d := range docs {
			if d == validDocs[pi] {
				idx = j
				break
			}
		}
		fmt.Fprintf(w, "    {%d, %s, %s, %s, %v, %s, %v},\n", idx, cstr(a.Action), cstr(a.Bucket), cstr(a.Object), a.Owner,
			cstr(condC(a.Cond)), allowed)
	}
	fmt.Fprintln(w, "};")
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: policygen tables|vectors")
		os.Exit(2)
	}
	switch os.Args[1] {
	case "tables":
		tables()
	case "vectors":
		vectors()
	}
}
