// Command golden prints reference outputs from the Go libraries MinIO uses, as
// a C include file, so the C ports in src/ are checked against the originals.
//
//	cd tools/golden && go run . > ../../tests/unit/golden_vectors.inc
package main

import (
	"crypto/sha1"
	"fmt"
	"hash/crc32"
	"hash/crc64"
	"math/bits"
	"math"
	"strings"

	"github.com/cespare/xxhash/v2"
	"github.com/dchest/siphash"
	"github.com/minio/highwayhash"
	"github.com/tinylib/msgp/msgp"
	"github.com/zeebo/xxh3"
	"encoding/binary"
)

// pattern returns n deterministic bytes; the C test regenerates the same input.
func pattern(n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = byte(i*7 + 3)
	}
	return b
}

func hexs(b []byte) string {
	var s strings.Builder
	for _, c := range b {
		fmt.Fprintf(&s, "\\x%02x", c)
	}
	return s.String()
}

func main() {
	fmt.Println("/* Generated by tools/golden. Do not edit. */")
	lens := []int{}
	for i := 0; i <= 260; i++ {
		lens = append(lens, i)
	}
	lens = append(lens, 511, 512, 513, 1023, 1024, 1025, 2047, 4096, 10000, 1<<20+17)

	// S3 additional checksums, as MinIO computes them (internal/hash/checksum.go).
	nvme := crc64.MakeTable(bits.Reverse64(0xad93d23594c93659))
	castagnoli := crc32.MakeTable(crc32.Castagnoli)
	fmt.Println("static const struct { size_t len; uint32_t crc32, crc32c; uint64_t crc64nvme; const char *sha1; } golden_cks[] = {")
	for _, n := range lens {
		p := pattern(n)
		s1 := sha1.Sum(p)
		fmt.Printf("  {%d, 0x%08xu, 0x%08xu, 0x%016xull, \"%s\"},\n", n, crc32.ChecksumIEEE(p), crc32.Checksum(p, castagnoli), crc64.Checksum(p, nvme), hexs(s1[:]))
	}
	fmt.Println("};")

	// SipHash-2-4 as MinIO's sipHashMod uses it (key = deployment ID bytes).
	fmt.Println("static const struct { size_t len; uint64_t k0, k1, sum; } golden_sip[] = {")
	for _, n := range lens {
		k0, k1 := uint64(0x0706050403020100), uint64(0x0f0e0d0c0b0a0908)
		if n%2 == 1 {
			k0, k1 = 0xdeadbeefcafebabe, 0x0123456789abcdef
		}
		fmt.Printf("  {%d, 0x%016xull, 0x%016xull, 0x%016xull},\n", n, k0, k1, siphash.Hash(k0, k1, pattern(n)))
	}
	fmt.Println("};")

	// MinIO placement: sipHashMod(object, sets, deploymentID) and hashOrder(key, n).
	id := [16]byte{0xa8, 0x9a, 0xd6, 0xa1, 0xf0, 0x17, 0x4e, 0x24, 0x9c, 0xf4, 0xe6, 0xfa, 0x82, 0x5e, 0xa2, 0x92}
	k0, k1 := binary.LittleEndian.Uint64(id[0:8]), binary.LittleEndian.Uint64(id[8:16])
	names := []string{"a", "photos/cat.jpg", "dir/big.bin", "bucket/object", "x/y/z/deep/key.txt", "unicode-\u00e9\u00e8", ""}
	fmt.Println("static const struct { const char *key; unsigned sets; unsigned set; unsigned n; int order[16]; } golden_place[] = {")
	for _, name := range names {
		for _, sets := range []uint64{1, 2, 3, 7, 16} {
			n := int(sets%15) + 2
			crc := crc32.Checksum([]byte(name), crc32.IEEETable)
			start := int(crc % uint32(n))
			var order []string
			for i := 1; i <= n; i++ {
				order = append(order, fmt.Sprint(1+((start+i)%n)))
			}
			fmt.Printf("  {\"%s\", %d, %d, %d, {%s}},\n", name, sets, siphash.Hash(k0, k1, []byte(name))%sets, n, strings.Join(order, ", "))
		}
	}
	fmt.Println("};")

	fmt.Println("static const struct { size_t len; uint64_t xxh64, xxh3; } golden_xxh[] = {")
	for _, n := range lens {
		p := pattern(n)
		fmt.Printf("  {%d, 0x%016xull, 0x%016xull},\n", n, xxhash.Sum64(p), xxh3.Hash(p))
	}
	fmt.Println("};")

	key := []byte("\x4b\xe7\x34\xfa\x8e\x23\x8a\xcd\x26\x3e\x83\xe6\xbb\x96\x85\x52\x04\x0f\x93\x5d\xa3\x9f\x44\x14\x97\xe0\x9d\x13\x22\xde\x36\xa0")
	fmt.Println("static const struct { size_t len; const char *hh256; } golden_hh[] = {")
	for _, n := range lens {
		h, _ := highwayhash.New(key)
		h.Write(pattern(n))
		fmt.Printf("  {%d, \"%s\"},\n", n, hexs(h.Sum(nil)))
	}
	fmt.Println("};")

	// msgpack encodings as tinylib/msgp produces them.
	type enc struct{ name string; b []byte }
	var encs []enc
	for _, v := range []int64{0, 1, 127, 128, 255, 256, 32767, 32768, 65535, 65536, math.MaxInt32, math.MaxInt32 + 1, math.MaxInt64, -1, -32, -33, -128, -129, -32768, -32769, math.MinInt32, math.MinInt32 - 1, math.MinInt64} {
		encs = append(encs, enc{fmt.Sprintf("int %d", v), msgp.AppendInt64(nil, v)})
	}
	for _, v := range []uint64{0, 127, 128, 255, 256, 65535, 65536, math.MaxUint32, math.MaxUint32 + 1, math.MaxUint64} {
		encs = append(encs, enc{fmt.Sprintf("uint %d", v), msgp.AppendUint64(nil, v)})
	}
	for _, n := range []int{0, 31, 32, 255, 256, 65536} {
		encs = append(encs, enc{fmt.Sprintf("str %d", n), trunc(msgp.AppendString(nil, strings.Repeat("a", n)))})
		encs = append(encs, enc{fmt.Sprintf("bin %d", n), trunc(msgp.AppendBytes(nil, make([]byte, n)))})
	}
	for _, n := range []uint32{0, 15, 16, 65535, 65536} {
		encs = append(encs, enc{fmt.Sprintf("map %d", n), msgp.AppendMapHeader(nil, n)})
		encs = append(encs, enc{fmt.Sprintf("array %d", n), msgp.AppendArrayHeader(nil, n)})
	}
	fmt.Println("static const struct { const char *name; const char *bytes; size_t n; } golden_msgp[] = {")
	for _, e := range encs {
		fmt.Printf("  {\"%s\", \"%s\", %d},\n", e.name, hexs(e.b), len(e.b))
	}
	fmt.Println("};")
}

// trunc keeps the header plus a few payload bytes; the payload itself is trivial.
func trunc(b []byte) []byte { return b[:min(8, len(b))] }
