// Command golden prints reference outputs from the Go libraries MinIO uses, as
// a C include file, so the C ports in src/ are checked against the originals.
//
//	cd tools/golden && go run . > ../../tests/unit/golden_vectors.inc
package main

import (
	"fmt"
	"math"
	"strings"

	"github.com/cespare/xxhash/v2"
	"github.com/minio/highwayhash"
	"github.com/tinylib/msgp/msgp"
	"github.com/zeebo/xxh3"
)

// pattern returns n deterministic bytes; the C test regenerates the same input.
func pattern(n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = byte(i*7 + 3)
	}
	return b
}

func hexs(b []byte) string {
	var s strings.Builder
	for _, c := range b {
		fmt.Fprintf(&s, "\\x%02x", c)
	}
	return s.String()
}

func main() {
	fmt.Println("/* Generated by tools/golden. Do not edit. */")
	lens := []int{}
	for i := 0; i <= 260; i++ {
		lens = append(lens, i)
	}
	lens = append(lens, 511, 512, 513, 1023, 1024, 1025, 2047, 4096, 10000, 1<<20+17)

	fmt.Println("static const struct { size_t len; uint64_t xxh64, xxh3; } golden_xxh[] = {")
	for _, n := range lens {
		p := pattern(n)
		fmt.Printf("  {%d, 0x%016xull, 0x%016xull},\n", n, xxhash.Sum64(p), xxh3.Hash(p))
	}
	fmt.Println("};")

	key := []byte("\x4b\xe7\x34\xfa\x8e\x23\x8a\xcd\x26\x3e\x83\xe6\xbb\x96\x85\x52\x04\x0f\x93\x5d\xa3\x9f\x44\x14\x97\xe0\x9d\x13\x22\xde\x36\xa0")
	fmt.Println("static const struct { size_t len; const char *hh256; } golden_hh[] = {")
	for _, n := range lens {
		h, _ := highwayhash.New(key)
		h.Write(pattern(n))
		fmt.Printf("  {%d, \"%s\"},\n", n, hexs(h.Sum(nil)))
	}
	fmt.Println("};")

	// msgpack encodings as tinylib/msgp produces them.
	type enc struct{ name string; b []byte }
	var encs []enc
	for _, v := range []int64{0, 1, 127, 128, 255, 256, 32767, 32768, 65535, 65536, math.MaxInt32, math.MaxInt32 + 1, math.MaxInt64, -1, -32, -33, -128, -129, -32768, -32769, math.MinInt32, math.MinInt32 - 1, math.MinInt64} {
		encs = append(encs, enc{fmt.Sprintf("int %d", v), msgp.AppendInt64(nil, v)})
	}
	for _, v := range []uint64{0, 127, 128, 255, 256, 65535, 65536, math.MaxUint32, math.MaxUint32 + 1, math.MaxUint64} {
		encs = append(encs, enc{fmt.Sprintf("uint %d", v), msgp.AppendUint64(nil, v)})
	}
	for _, n := range []int{0, 31, 32, 255, 256, 65536} {
		encs = append(encs, enc{fmt.Sprintf("str %d", n), trunc(msgp.AppendString(nil, strings.Repeat("a", n)))})
		encs = append(encs, enc{fmt.Sprintf("bin %d", n), trunc(msgp.AppendBytes(nil, make([]byte, n)))})
	}
	for _, n := range []uint32{0, 15, 16, 65535, 65536} {
		encs = append(encs, enc{fmt.Sprintf("map %d", n), msgp.AppendMapHeader(nil, n)})
		encs = append(encs, enc{fmt.Sprintf("array %d", n), msgp.AppendArrayHeader(nil, n)})
	}
	fmt.Println("static const struct { const char *name; const char *bytes; size_t n; } golden_msgp[] = {")
	for _, e := range encs {
		fmt.Printf("  {\"%s\", \"%s\", %d},\n", e.name, hexs(e.b), len(e.b))
	}
	fmt.Println("};")
}

// trunc keeps the header plus a few payload bytes; the payload itself is trivial.
func trunc(b []byte) []byte { return b[:min(8, len(b))] }
