#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""src/metrics/minio-catalog.tsv + extra-catalog.tsv + buckets-catalog.tsv ->
src/metrics/catalog.inc: the names, types and help of every metric MinIO can
emit (v2 and v3), and the few of Buckets' own (buckets_*, only where their
feature is on): the only names bucketsd emits.

  tools/metrics-catalog/gen-c.py
"""
import json
import os

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "src", "metrics")
TYPES = {"gaugeMetric": "GAUGE", "gauge": "GAUGE", "counterMetric": "COUNTER", "counter": "COUNTER",
         "histogramMetric": "HISTOGRAM", "histogram": "HISTOGRAM", "summary": "SUMMARY", "": "GAUGE"}  # "": MinIO leaves Type unset (a gauge)
v2, v2r, v3 = {}, {}, {}
for fn in ("minio-catalog.tsv", "extra-catalog.tsv", "buckets-catalog.tsv"):
    for line in open(os.path.join(root, fn)):
        if line.startswith("#") or not line.strip():
            continue
        f = line.rstrip("\n").split("\t")
        kind, where, name, typ, hlp = f[:5]
        labels = f[5] if len(f) > 5 else ""
        v3side = kind == "V3" or (kind == "X" and where.startswith("/"))
        # the resource endpoint reuses node names with its own help
        table = v3 if v3side else v2r if where == "resource" else v2
        if name in table:  # the first description wins (MinIO's duplicate name, see README)
            continue
        table[name] = (TYPES[typ], json.loads(hlp), labels, where)


def c(s):
    return json.dumps(s)  # C and JSON string escapes agree here


out = ["/* Generated by tools/metrics-catalog/gen-c.py from minio-catalog.tsv,",
       " * extra-catalog.tsv and buckets-catalog.tsv: do not edit. */", ""]
for tname, table in (("k_catalog_v2", v2), ("k_catalog_v2_resource", v2r), ("k_catalog_v3", v3)):
    out.append("static const buckets_metric_def %s[] = {" % tname)
    for name in sorted(table):
        t, h, labels, where = table[name]
        out.append("    {%s, BUCKETS_MT_%s, %s, %s}," % (c(name), t, c(h), c(where if tname.endswith("v3") else "")))
    out.append("};")
    out.append("")
open(os.path.join(root, "catalog.inc"), "w").write("\n".join(out))
print("v2 %d, v2 resource %d, v3 %d" % (len(v2), len(v2r), len(v3)))
