#!/usr/bin/env python3
"""Generate docs/parity.md: every API handler MinIO registers, and Buckets' status.

The route list is extracted from a MinIO checkout so nothing is forgotten; the
status of each handler is maintained in STATUS below and updated as features land.

usage: scripts/gen-parity.py ~/minio RELEASE.2025-10-15T17-29-55Z
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DONE, PARTIAL = "done", "partial"

# handler -> (status, note). Anything absent is "todo".
STATUS = {
    # S3 (single drive; SSE, versioning, object lock, tagging arrive in later phases)
    "ListBucketsHandler": (DONE, ""),
    "PutBucketHandler": (PARTIAL, "object-lock flag pending"),
    "HeadBucketHandler": (DONE, ""),
    "DeleteBucketHandler": (PARTIAL, "no x-minio-force-delete"),
    "GetBucketLocationHandler": (DONE, ""),
    "GetBucketVersioningHandler": (PARTIAL, "always reports unversioned"),
    "ListObjectsV1Handler": (DONE, ""),
    "ListObjectsV2Handler": (DONE, ""),
    "ListObjectsV2MHandler": (DONE, "metadata=true extension"),
    "PutObjectHandler": (PARTIAL, "no SSE/tagging/object-lock/versioning yet"),
    "GetObjectHandler": (PARTIAL, "no SSE/versioning/zip-extract yet"),
    "HeadObjectHandler": (PARTIAL, "no SSE/versioning yet"),
    "DeleteObjectHandler": (PARTIAL, "unversioned buckets only"),
    "DeleteMultipleObjectsHandler": (PARTIAL, "unversioned buckets only"),
    "CopyObjectHandler": (PARTIAL, "no SSE/tagging directives yet"),
    "CopyObjectPartHandler": (DONE, ""),
    "NewMultipartUploadHandler": (DONE, ""),
    "PutObjectPartHandler": (DONE, ""),
    "CompleteMultipartUploadHandler": (DONE, ""),
    "AbortMultipartUploadHandler": (DONE, ""),
    "ListObjectPartsHandler": (DONE, ""),
    "ListMultipartUploadsHandler": (PARTIAL, "per-object listing, like MinIO; no pagination markers"),
    "GetObjectAttributesHandler": (DONE, ""),
    "PostPolicyBucketHandler": (PARTIAL, "no SSE form fields yet"),
    "GetBucketACLHandler": (DONE, "canned private, as MinIO"),
    "PutBucketACLHandler": (DONE, "canned private, as MinIO"),
    "GetObjectACLHandler": (DONE, "canned private, as MinIO"),
    "PutObjectACLHandler": (DONE, "canned private, as MinIO"),
    # health
    "LivenessCheckHandler": (DONE, ""),
    "ReadinessCheckHandler": (DONE, ""),
    "ClusterCheckHandler": (PARTIAL, "single node only"),
    "ClusterReadCheckHandler": (PARTIAL, "single node only"),
}

SOURCES = [
    ("S3 API", "cmd/api-router.go", r"api\.([A-Za-z0-9]+Handler)"),
    ("Admin API (madmin / mc admin)", "cmd/admin-router.go", r"adminAPI\.([A-Za-z0-9]+)"),
    ("STS", "cmd/sts-handlers.go", r"sts\.(AssumeRole[A-Za-z]*)\)"),
    ("KMS API", "cmd/kms-router.go", r"kmsAPI\.([A-Za-z0-9]+)"),
    ("Metrics", "cmd/metrics-router.go", r"(metricsHandler|metricsServerHandler|metricsNodeHandler|"
     r"metricsBucketHandler|metricsResourceHandler)\b"),
    ("Health", "cmd/healthcheck-router.go", r"([A-Za-z]+CheckHandler)"),
]

ICON = {DONE: "✅", PARTIAL: "🟡", "todo": "⬜"}


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    minio, ref = sys.argv[1], sys.argv[2]
    out = [
        "# Feature parity with MinIO",
        "",
        f"Generated by `scripts/gen-parity.py` from MinIO `{ref}`. Every handler MinIO",
        "registers is listed; statuses live in the script's `STATUS` table.",
        "",
        "✅ done · 🟡 partial · ⬜ not started",
        "",
    ]
    totals = {DONE: 0, PARTIAL: 0, "todo": 0}
    sections = []
    for title, path, pattern in SOURCES:
        src = subprocess.check_output(["git", "-C", minio, "show", f"{ref}:{path}"], text=True)
        names = sorted(set(re.findall(pattern, src)))
        rows = []
        for n in names:
            status, note = STATUS.get(n, ("todo", ""))
            totals[status] += 1
            rows.append(f"| {ICON[status]} | `{n}` | {note} |")
        done = sum(1 for n in names if STATUS.get(n, ("todo",))[0] == DONE)
        sections += [f"## {title} ({done}/{len(names)})", "", f"Source: `{path}`", "",
                     "| | Handler | Notes |", "|---|---|---|"] + rows + [""]
    total = sum(totals.values())
    out += [f"**Overall:** {totals[DONE]} done, {totals[PARTIAL]} partial, {totals['todo']} not started "
            f"({total} handlers).", ""]
    out += sections
    out += [
        "## Beyond the routers",
        "",
        "Subsystems with no single handler, tracked by phase in `docs/architecture.md`:",
        "erasure coding + bitrot and xl.meta v2 (done, single node), distributed locking, healing, scanner,",
        "ILM/tiering, bucket + site replication, notifications (10 targets), audit,",
        "SSE-S3/KMS/C, compression, S3 Select, SFTP/FTP, batch jobs, decommission/rebalance,",
        "IAM (LDAP/OIDC/plugins/OPA), operator, console.",
        "",
    ]
    with open(os.path.join(ROOT, "docs/parity.md"), "w") as f:
        f.write("\n".join(out))
    print(f"docs/parity.md: {totals[DONE]} done, {totals[PARTIAL]} partial, {total} total")


if __name__ == "__main__":
    main()
