#!/usr/bin/env python3
"""Generate the S3 API error table from MinIO's cmd/api-errors.go.

Buckets must return byte-identical error codes, messages and HTTP statuses so
existing SDKs and conformance suites behave the same. Rather than copy them by
hand, this script extracts the errorCodes map from a MinIO checkout.

usage: scripts/gen-s3-errors.py ~/minio RELEASE.2025-10-15T17-29-55Z
writes: src/s3/errors_gen.h, src/s3/errors_gen.c
"""
import http
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GO_STRING = r'"(?:[^"\\]|\\.)*"'


def go_status_to_int(expr, table):
    expr = expr.strip()
    if expr.isdigit():
        return int(expr)
    m = re.fullmatch(r"http\.Status(\w+)", expr)
    if m:
        snake = re.sub(r"(?<!^)(?=[A-Z])", "_", m.group(1)).upper()
        return int(http.HTTPStatus[snake])
    m = re.fullmatch(r"errorCodes\[(\w+)\]\.HTTPStatusCode", expr)
    if m and m.group(1) in table:
        return table[m.group(1)][2]
    return None


def concat_go_strings(expr):
    """Joins "a" + "b" literal concatenations; returns None for computed values."""
    parts = re.findall(GO_STRING, expr)
    rest = re.sub(GO_STRING, "", expr)
    if parts and re.fullmatch(r"[\s+]*", rest):
        return "".join(bytes(p[1:-1], "utf-8").decode("unicode_escape") for p in parts)
    return None


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    minio, ref = sys.argv[1], sys.argv[2]
    src = subprocess.check_output(["git", "-C", minio, "show", f"{ref}:cmd/api-errors.go"], text=True)
    start = src.index("var errorCodes = errorCodeMap{")
    end = src.index("\n}\n", start)
    body = src[start:end]

    table = {}
    order = []
    for m in re.finditer(r"^\t(Err\w+): \{\n(.*?)^\t\},", body, re.S | re.M):
        name, fields = m.group(1), m.group(2)
        code = re.search(r"Code:\s*(" + GO_STRING + ")", fields)
        desc = re.search(r"Description:\s*(.*?),\s*\n\s*HTTPStatusCode", fields, re.S)
        status = re.search(r"HTTPStatusCode:\s*([^,\n]+)", fields)
        if not (code and desc and status):
            continue
        d = concat_go_strings(desc.group(1))
        s = go_status_to_int(status.group(1), table)
        if d is None or s is None:
            print(f"skip {name}: computed description or status", file=sys.stderr)
            continue
        table[name] = (concat_go_strings(code.group(1)), d, s)
        order.append(name)

    def cname(go):
        return "BUCKETS_" + re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", go).upper()

    header = [
        "/* Generated by scripts/gen-s3-errors.py from MinIO " + ref + " cmd/api-errors.go.",
        " * Do not edit by hand. SPDX-License-Identifier: AGPL-3.0-or-later */",
        "#ifndef BUCKETS_S3_ERRORS_GEN_H",
        "#define BUCKETS_S3_ERRORS_GEN_H",
        "",
        "typedef enum {",
        "  BUCKETS_ERR_NONE = 0,",
    ]
    header += [f"  {cname(n)}," for n in order]
    header += ["  BUCKETS_ERR__COUNT", "} buckets_s3_error;", "", "#endif", ""]

    impl = [
        "/* Generated by scripts/gen-s3-errors.py. Do not edit by hand.",
        " * SPDX-License-Identifier: AGPL-3.0-or-later */",
        '#include "s3/errors.h"',
        "",
        "const buckets_s3_error_info buckets_s3_errors[BUCKETS_ERR__COUNT] = {",
        '    [BUCKETS_ERR_NONE] = {"", "", 200},',
    ]
    for n in order:
        code, desc, status = table[n]
        impl.append(f'    [{cname(n)}] = {{"{c_escape(code)}", "{c_escape(desc)}", {status}}},')
    impl += ["};", ""]

    with open(os.path.join(ROOT, "src/s3/errors_gen.h"), "w") as f:
        f.write("\n".join(header))
    with open(os.path.join(ROOT, "src/s3/errors_gen.c"), "w") as f:
        f.write("\n".join(impl))
    print(f"generated {len(order)} S3 error codes")


if __name__ == "__main__":
    main()
